//config/defaultRoomTypes.js

export const defaultRoomTypes = [
  {
    type: 'standard',
    nameKor: '스탠다드',
    nameEng: 'Standard',
    price: 80000,
    stock: 10,
    aliases: ['standard'],
  },
  {
    type: 'premium',
    nameKor: '프리미엄',
    nameEng: 'Premium',
    price: 90000,
    stock: 10,
    aliases: ['premium'],
  },
  {
    type: 'executive',
    nameKor: '이그제큐티브',
    nameEng: 'Executive',
    price: 100000,
    stock: 10,
    aliases: ['executive'],
  },
  {
    type: 'twin',
    nameKor: '트윈',
    nameEng: 'Twin',
    price: 110000,
    stock: 10,
    aliases: ['twin'],
  },
  {
    type: 'pcroom',
    nameKor: 'PC룸',
    nameEng: 'PC Room',
    price: 110000,
    stock: 10,
    aliases: ['pcroom'],
  },
  {
    type: 'styleroom',
    nameKor: '스타일러룸',
    nameEng: 'Styler Room',
    price: 90000,
    stock: 10,
    aliases: ['styleroom'],
  },
  {
    type: 'hinokki',
    nameKor: '히노끼',
    nameEng: 'Hinokki',
    price: 150000,
    stock: 10,
    aliases: ['hinokki'],
  },
];
